codecov:
  token: 7c7bccd2-238a-441d-ba3e-63fdc8e3c1bf  # Required if not using GitHub Actions or other CI integrations
  require_ci_to_pass: yes
  max_report_age: off

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        target: 80%  # Minimum coverage required
        threshold: 2%  # Allowed drop in coverage
    patch:
      default:
        target: 80%
        threshold: 2%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true  # Only post a comment if coverage changes

parsers:
  javascript:
    enable_partials: yes

ignore:
  - "node_modules"
  - "tests/*"
  - "coverage/*"
  - "**/*.test.js"
  - "**/*.spec.js"
