name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests with Coverage
        run: npm test -- --coverage

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v5
        with:
          token: 7c7bccd2-238a-441d-ba3e-63fdc8e3c1bf # Add this secret in GitHub Actions
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true